# Generated by Django 6.0.5 on 2026-05-27 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='hierarchy',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', False)), fields=('name', 'parent'), name='unique_hierarchy_node'),
        ),
        migrations.AddConstraint(
            model_name='hierarchy',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', True)), fields=('name',), name='unique_hierarchy_root'),
        ),
        migrations.AddConstraint(
            model_name='link',
            constraint=models.UniqueConstraint(fields=('url', 'hierarchy'), name='unique_folder_link'),
        ),
    ]
